server:
  port: 8080
spring:
  application:
    name: user-ws
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url:
         http://localhost:8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
